version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=roman
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db:/var/lib/postgresql/data
    networks:
      - patients-net  

networks:
  patients-net:
